Task-10_Added the files necessary for doing the indicated requirements. Adjusted the Readme.md file according to demand.
verginia/FrontEnd-Tasks-Repository pull request #8
Opened 2024-04-10 10:22 UTC by verginia

2024-04-15 14:25 UTC, ngoncearu requested changes

2024-04-15 14:25 UTC, ngoncearu commented on app/css/boxModel.css
> +box-sizing: padding-box;
avem doua valori pentru box -sizing:
``box-sizing: border-box; box-sizing: content-box;``
Padding-box nu exista

2024-04-17 09:07 UTC, verginia commented on app/css/boxModel.css
> +box-sizing: padding-box;
fixed

2024-04-26 12:50 UTC, ngoncearu commented
let's solve conflicts and merge it!

2024-04-29 08:44 UTC, merged